version: '3.7'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: redhat8
  

  www:
   depends_on: 
   - db
   image: php:7.4.18-apache:
   volumes:
   - "./test/:/var/www/html"
   ports: 
   - 80:80
   - 443:443 
   